### PR TITLE
ElmahIoTarget - Changed to AsyncTaskTarget with support for CreateBulk

### PR DESCRIPTION
**Pull request by snakefoot**
See also: https://github.com/NLog/NLog/wiki/How-to-write-a-custom-async-target

### CODE REVIEW

**Comment by ThomasArdal** [comment]
This is absolutely AWESOME, @snakefoot! Bulk and async was on the TODO list for sure. Thank you very much.

**Comment by ThomasArdal** [comment]
@snakefoot do I need to do anything else to trigger NLog to log now? When running the Elmah.Io.NLog.Console sample, `WriteAsyncTask` is never invoked.

**Comment by snakefoot** [comment]
Have updated `Elmah.Io.NLog.Console`-project to use NLog 4.6.5

**Comment by ThomasArdal** [comment]
Ahh, of course 👍 Do I need to do anything to make sure that all messages are stored before exiting the process. Serilog has a `Log.CloseAndFlush();` that must be called before exit and wondering if there is a similar construct in NLog?

**Comment by snakefoot** [comment]
NLog has automatic flush on shutdown, but it is not reliable for network-based-targets, but is more for console and file-targets.

There are the following methods in NLog:
```c#
NLog.LogManager.Flush();  // Flushes the current messages without closing down
NLog.LogManager.Shutdown();  // Flushes and closes all targets (recommended to call this just before application exit)
```

**Comment by ThomasArdal** [comment]
PARTYYYY!!!

**Pull request merged**
