### PR TITLE
Added NetStandard2.0 to targetframeworks. Introduced ${environment-user}

### PR DESCRIPTION
**Pull request by snakefoot**
See also: https://github.com/NLog/NLog/wiki/Environment-User-Layout-Renderer

### CODE REVIEW

**Comment by ThomasArdal** [comment]
@snakefoot Good stuff 👍 

Quick question. While merging this, I'm changing a few small things like improving the user agent and more. I also want to think about if the current timeout (5 seconds) is good or not. 5 seconds is the default since logging to elmah.io originally happened during a web request. I'm not an expert in `AsyncTaskTarget` but does that mean that the time consumed in the target won't affect the code generating the log messages? In that case, I may want to increase the default timeout.

**Comment by snakefoot** [comment]
When writing to `AsyncTaskTarget` then one is writing directly into an in-memory-queue (default max-size is 10000 events and discards on overflow).

See also: https://github.com/NLog/NLog/wiki/How-to-write-a-custom-async-target

Because `CreateBulkAndNotifyAsync` does not seem to support cancellation-token, then the timeout-support is rather limited. But you are welcome to increase `TaskTimeoutSeconds` it will just delay the next task, when the previous task never completed.

**Comment by ThomasArdal** [comment]
Ok, that's great. Increasing the default timeout would probably be the right thing to do then. As long as the HTTP timeout is never set to more than `TaskTimeoutSeconds` 👍

**Comment by snakefoot** [comment]
Curious where "5 secs" comes from:

https://github.com/elmahio/elmah.io.nlog/blob/3a83593592c6ccae1454af75d643e7b191094d5d/src/Elmah.Io.NLog/ElmahIoTarget.cs#L108

**Comment by snakefoot** [comment]
Ahh now I see:

https://github.com/elmahio/elmah.io.nlog/blob/3a83593592c6ccae1454af75d643e7b191094d5d/src/Elmah.Io.NLog/ElmahIoTarget.cs#L198

**Comment by ThomasArdal** [comment]
Yep. 5 seconds is a pretty useless timeout. It's from the time where elmah.io only supported sync logging from ASP.NET applications. In that case, it was important that elmah.io logging didn't slow down generating the response to the user "too much". 5 seconds was the compromise to support occasional slow API requests. All of the integrations now set a custom timeout, depending on how each integration is implemented. In the case of the NLog target, 5 seconds doesn't really make sense (IMO).

**Comment by ThomasArdal** [comment]
https://www.nuget.org/packages/elmah.io.nlog/3.6.79-pre

party

**Pull request merged**
